### ISSUE TITLE
How to configure the library with microfrontends?

### ISSUE THREAD

**Issue by alanmatiasdev** [keycloakify/oidc-spa#32]
I have a set of micro frontends divided into a single page layout: header, content. It turns out that, in general, the platform displays the header and content at once. Since I need user information in both contexts, I include the library for both applications. This causes the library to create different states in the browser's local storage and when opening a new browser tab I get the message that no state was found in the browser. Is there any guidance for this scenario?

`OIDC initialization error of type "unknown": No matching state found in storage`

**Comment by alanmatiasdev** [comment]
I made this small project to try to exemplify the issue, but I couldn't reproduce the error that is notified, however, it reproduces the issue of multiple states in local storage (is this expected behavior?). This project simulates an application of a real case that I have. If you try to run it and encounter any difficulties, please let me know.

https://github.com/alanmatiasdev/react-mfr-oidc-example

![image](https://github.com/user-attachments/assets/48ff64e2-c12e-42d8-a097-5b0f73f0776a)

I'm trying to reproduce the initial behavior: when opening a new tab, it apparently can't read the state of the local storage and returns the error above.

**Comment by alanmatiasdev** [comment]
I found something, when I open the new tab, the session storage is empty and the user recovery function searches for it there. I'm still analyzing it

https://github.com/keycloakify/oidc-spa/blob/a06808eb695f6537cb1716459a9594dfd2e0875b/src/oidc.ts#L870

https://github.com/authts/oidc-client-ts/blob/8181652f609242dd14ee1ae4f6b82a9a5116f966/src/UserManager.ts#L775-L785

**Comment by alanmatiasdev** [comment]
@garronej I managed to resolve the issue of the error mentioned above (regarding opening new tabs) by changing the userStore from sessionStorage to localStorage. I made the change because sessionStorage does [not share stored](https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage) data between tabs even if a new tab is from the same source. Would this be a bad practice in any way or can we implement this possibility in the library?

![image](https://github.com/user-attachments/assets/3d5f2aed-8e22-4f75-8adb-a3ea1901c977)

https://github.com/keycloakify/oidc-spa/blob/a06808eb695f6537cb1716459a9594dfd2e0875b/src/oidc.ts#L363-L388

However the multiple states still remain and I believe it is related to having multiple instances of the lib on the page.

**Comment by garronej** [comment]
First off, thank you for taking the time to investigate this so thoroughly.

> Would this be a bad practice in any way, or can we implement this possibility in the library?

Unfortunately, this isn’t ideal. The whole point of opening an iframe in the background and getting the auth server to redirect to `silent-sso.htm` is to avoid relying on `localStorage` and instead use HTTP-only cookies. If you use `localStorage`, your app won’t pass a security audit.

Just to make sure we’re on the same page: I don’t believe there’s a known issue here, as we can restore the session using silent SSO. Can you confirm that you’re unable to reproduce any issues or suspicious behavior with the demo apps, like the [TanStack Router demo app](https://example-tanstack-router.oidc-spa.dev/)?

> However, the multiple states still remain, and I believe it is related to having multiple instances of the lib on the page.

That’s concerning. You should have at most two session storage entries—something isn’t behaving as expected.

I had some trouble running your demo repo:

![image](https://github.com/user-attachments/assets/fbfe078d-ac94-49d7-bef6-4f2f9b0b4c4d)

Could you update it to use my public Keycloak instance, which I use for my test project? You can check out the example here:  
https://github.com/keycloakify/oidc-spa/blob/main/examples/tanstack-router-file-based/.env.local.sample

This would make it easier for me, so we don’t have to spin up a Keycloak Docker container for testing, and we can rule out any issue related to a specific Keycloak configuration.

I don’t have much experience with microfrontends, but my colleague @ddecrulle is quite knowledgeable in that area. If you can set up a straightforward reproduction path, there’s a good chance we’ll be able to figure it out.

By the way, what brought you to this library? I’m curious since it still has a relatively small user base, and I’d love to know what convinced you to give it a try.

**Comment by alanmatiasdev** [comment]
> Just to make sure we're on the same page: I don't believe there's a known issue here, as we can restore the session using silent SSO. Can you confirm that you’re unable to reproduce any issues or suspicious behavior with the demo apps, like the TanStack Router demo app?

I will test and return with feedback.

> Could you update it to use my public Keycloak instance, which I use for my test project? You can check out the example here: https://github.com/keycloakify/oidc-spa/blob/main/examples/tanstack-router-file-based/.env.local.sample

Yes, of course. I updated the repository https://github.com/alanmatiasdev/react-mfr-oidc-example

> By the way, what brought you to this library? I’m curious since it still has a relatively small user base, and I’d love to know what convinced you to give it a try.

I have been using Keycloakify for some time now, since implementing oidc-spa. I tested it in a development environment and, based on my analysis, I found the library to be more stable than the implementation we had. I chose to adopt it due to its simplicity of implementation.

**Comment by alanmatiasdev** [comment]
> Just to make sure we're on the same page: I don't believe there's a known issue here, as we can restore the session using silent SSO. Can you confirm that you’re unable to reproduce any issues or suspicious behavior with the demo apps, like the TanStack Router demo app?

It is working correctly. I believe this has something to do with the microfrontends configuration.

**Comment by ddecrulle** [comment]
Thanks for the report, I'm having the same issue as @garronej :

![image](https://github.com/user-attachments/assets/729d0dfc-898c-4c97-8fa0-3139ee1b6c46)

**Comment by alanmatiasdev** [comment]
Strange. Did you run yarn start from the root of the project? Are all applications running correctly? Can you verify that `localhost:5173/src/spa.tsx` returns a vite build code?

![image](https://github.com/user-attachments/assets/7256198d-29eb-46c6-9c64-03c535050d36)

**Comment by ddecrulle** [comment]
The issue occurred because I had something running on port 5173, and the monorepo doesn’t handle port changes well.I can reproduce now.

**Comment by garronej** [comment]
Can you guys give a try with `5.3.0-rc.1` ?

**Comment by alanmatiasdev** [comment]
> Unfortunately, this isn’t ideal. The whole point of opening an iframe in the background and getting the auth server to redirect to silent-sso.htm is to avoid relying on localStorage and instead use HTTP-only cookies. If you use localStorage, your app won’t pass a security audit.

Could we include the possibility for the user to change the storage, perhaps marking it as unsafe?

> Can you guys give a try with `5.3.0-rc.1` ?

I will try and get back to you.

**Comment by garronej** [comment]
> Could we include the possibility for the user to change the storage, perhaps marking it as unsafe?  

I would prefer not to. While it's rellevent to be offered as an option for React Native or Electron desktop app, OIDC-SPA is specifically designed for web application.  
In this context, persisting the session on the local sorage is fundamentally an unsafe approach and shouldn't be considered.  

> I will try and get back to you.  

Did you had a chance to try it? There's good chances that the problem has been fixed in the latest release of oidc-spa.

**Comment by alanmatiasdev** [comment]
> Did you had a chance to try it? There's good chances that the problem has been fixed in the latest release of oidc-spa.

I haven't had time to check yet. I should check by the end of the week and get back to you.

**Comment by alanmatiasdev** [comment]
> Did you had a chance to try it? There's good chances that the problem has been fixed in the latest release of oidc-spa.

The multi-state behavior still remains in v5.4.0. I notice it occurs mainly when a new tab is opened.

![image](https://github.com/user-attachments/assets/3e3f14c6-7f09-431b-8736-2b7c835bd4e1)

@ddecrulle could you tell me if, in my microfrontend scenario, it would be an alternative to remove the libraries from the react application and leave it in the root (the orchestrator with the single-spa).

**Comment by ddecrulle** [comment]
> @ddecrulle could you tell me if, in my microfrontend scenario, it would be an alternative to remove the libraries from the react application and leave it in the root (the orchestrator with the single-spa).

This approach can work but comes with significant limitations. You cannot secure anything in the remote application, and if you need tokens, it will be tricky to manage them, which will significantly impact the developer experience. Additionally, you will create implicit dependencies between the host and the remote, which could lead to maintenance challenges.

I will try to understand why there is multistate. Maybe it's related to the oidc-spa_config_hash

**Comment by ddecrulle** [comment]
The issue you're experiencing is caused by a bug in `oidc-client-ts` and is not related to your microfrontend setup. Specifically, when you are not logged in, each refresh of the app adds another entry to `localStorage`. Once you log in, this behavior stops. In your setup, this effect is being multiplied by three.

Here is a detailed explanation of the behavior:

When calling `createReactOidc`, an instance of `UserManager` is created, and the code attempts to perform a [silent signin](https://github.com/keycloakify/oidc-spa/blob/main/src/oidc.ts#L1159). In `oidc-client-ts`, this triggers [this method](https://github.com/authts/oidc-client-ts/blob/1cc7829d2041ab092d9071ba5205e61cd6e991eb/src/UserManager.ts#L302), which calls [`this._signin`](https://github.com/authts/oidc-client-ts/blob/1cc7829d2041ab092d9071ba5205e61cd6e991eb/src/UserManager.ts#L265). 

This, in turn, calls the [`createSigninRequest` method from OidcClient](https://github.com/authts/oidc-client-ts/blob/1cc7829d2041ab092d9071ba5205e61cd6e991eb/src/UserManager.ts#L512), which invokes [SigninRequest.create](https://github.com/authts/oidc-client-ts/blob/1cc7829d2041ab092d9071ba5205e61cd6e991eb/src/OidcClient.ts#L129). Since no `id` is provided, it leads to running this code: [State.ts](https://github.com/authts/oidc-client-ts/blob/1cc7829d2041ab092d9071ba5205e61cd6e991eb/src/State.ts#L26-L27), where `CryptoUtils.generateUUIDv4()` is used to generate a new ID on every page refresh.

**Comment by garronej** [comment]
This is something that is important to us as well. I'll adress it as soon I have the time.

**Comment by garronej** [comment]
Hello @alanmatiasdev,  

I've finaly got around fixing the problem pointed out by @ddecrulle.  

Let us know if `oidc-spa@5.4.2` fixes the issue.

**Comment by alanmatiasdev** [comment]
Thanks for the quick response @garronej. I will test again.

**Comment by ddecrulle** [comment]
Hello, can you confirme that the problem is solved so I can close ?

**Comment by alanmatiasdev** [comment]
The problem of multiple entries in local storage has been resolved, but this has certainly been happening frequently. When opening a new application tab, it does not recognize the user's authentication status. I have not tested it outside the context of microfrontends.

[Screencast from 27-10-2024 12:49:24.webm](https://github.com/user-attachments/assets/3ed11c1a-f1bb-4e77-ae28-4d03ff4a881a)

**Comment by ddecrulle** [comment]
Great, the issue with multiple entries is fixed. I don’t understand the remaining issue.

I’ve tested it:

- When I’m logged in, if I open a new tab, I’m still logged in (on a browser that doesn’t block third-party cookies).
- If this issue is indeed related to third-party cookies, there’s not much we can do. The best solution would be to host the IDP on the same domain as the app.

You can find more documentation [here](https://docs.oidc-spa.dev/resources/end-of-third-party-cookies).

To clarify:

- This only affects **Frontend 1**, which can be accessed without authentication.
- Since **Frontend 2** requires authentication, it will call the IDP every time and will recognize the user.

**Comment by garronej** [comment]
Thanks @ddecrulle,  

If you can provide a reproduction path using the creadentials of our Keycloak we can address it...  

https://github.com/keycloakify/oidc-spa/blob/main/examples/tanstack-router-file-based/.env.local.sample

**Comment by garronej** [comment]
Hello @alanmatiasdev,  

I finally figured out—months later—why it wasn’t working in microfrontend setups.  

It’s probably too late for you, but v6 should now work without any issues.  

Here’s the migration guide from v5 to v6: [Migration Guide](https://docs.oidc-spa.dev/release-notes).

**Comment by alanmatiasdev** [comment]
@garronej thanks for the feedback, I ended up making a local patch to be able to use the library but still having a lot of problems. Could you point to the commit so I can see what was done to fix it or explain what it was?

**Comment by garronej** [comment]
It's not just a single commit—I rewrote most of the library. However, the relevant changes related to microfrontend support are here:

Previously, we had a global variable scoped to the module:

🔗 [Old implementation](https://github.com/keycloakify/oidc-spa/blob/8c3f83b57235c1f970fef2bbfdf40b48c2acc5c0/src/oidc.ts#L213)

Now, the global is scoped to the entire application:

🔗 [New implementation](https://github.com/keycloakify/oidc-spa/blob/dd683ec5fddb79231435fcce50a0007e2f37c8ba/src/oidc/createOidc.ts#L115-L137)

### Why is this important?
There must be only **one instance** of the OIDC client for a given configuration. The `createOidc()` function **must be memoized**, otherwise, different microfrontend applications will race to handle authentication responses, leading to conflicts.

### Ensuring consistent initialization
You are responsible for ensuring that **all applications** using `oidc-spa` initialize it with the **same parameters**; otherwise, you will encounter unpredictable behavior.

For example, if two different applications initialize `oidc-spa` with the same `issuerUri` and `clientId`, then **all other parameters must also match**.

✅ **Correct setup across microfrontends**
#### `packages/frontend1/src/oidc.ts`
```tsx
import { createReactOidc } from "oidc-spa/react";

export const { OidcProvider, getOidc, useOidc } = createReactOidc({
  clientId: "example-tanstack-router",
  issuerUri: "https://cloud-iam.oidc-spa.dev/realms/oidc-spa",
  publicUrl: "/",
  accessTokenSchema: ...
});
```

#### `packages/frontend2/src/oidc.ts`
```tsx
import { createReactOidc } from "oidc-spa/react";

export const { OidcProvider, getOidc, useOidc } = createReactOidc({
  clientId: "example-tanstack-router",
  issuerUri: "https://cloud-iam.oidc-spa.dev/realms/oidc-spa",
  // Ensure this matches frontend1
  publicUrl: "/",
  accessTokenSchema: ...
});
```

### A common mistake to avoid
You **cannot** set `autoLogin: true` (formerly `isAuthGloballyRequired: true`) in one app but not in another—it **must** be consistent across all microfrontends.

If you need to assert that the user is logged in within `frontend2`, do this:

```tsx
const { /*...*/ } = useOidc({ assert: "user logged in" });

getOidc().then(oidc => {
  if (!oidc.isUserLoggedIn) {
    throw new Error("Logic error: The user is supposed to be authenticated in frontend2.");
  }

  // ...
});
```

By following these guidelines, you can ensure a **stable and conflict-free** authentication experience across your microfrontend applications.

**Comment by garronej** [comment]
I realized that my implementation of Micro Frontend support made token theft trivially easy in the presence of malicious code (XSS) within your app.
I’m rolling it back for now until I can implement a more secure approach.

For now, version **6.9.11** will be the last release compatible with Micro Frontend.
